#WiFi Credentials
#ssid = "osprey"
#wlan_pass = "birdsofprey"
ssid = "owl"
wlan_pass = "dodgyiot"
#ssid = "W3Z-83B3"
#wlan_pass = "Herdyhigh07"
mqtt_server = "condor"
ftphost = "condor"
ftpuser = "piftp"
ftppw = "Herdw1ckSheep:)"
