#WiFi Credentials
#ssid = "osprey"
#wlan_pass = "birdsofprey"
#ssid = "owl"
#wlan_pass = "dodgyiot"
ssid = "W3Z-83B3"
wlan_pass = "Herdyhigh07"
ftphost = "192.168.1.113"
ftpuser = "pi"
ftppw = "Pepperm1nt"
